### ISSUE TITLE
Great work

### ISSUE THREAD

**Issue by muggsyd** [jaloji/docker-pyautorescene#1]
I already run autorescene in a docker container. It's great to see the work you are doing. The issue I faced during my testing of my own build, was that the version of Python needed to be 3.7 ( I think) or else I ran into issues. Also, do you need to download the rar archives for preparerar.py as well?

**Comment by muggsyd** [comment]
This is the image my build is based on
FROM python:3.7.9-alpine3.12 and these are the only packages I add to it from Alpine
apk add curl unrar git

I also don't think a username/password is required to scrap srrdb.com either
This is where I get my rar executables from
git clone https://github.com/dryes/rarlinux.git

**Comment by jaloji** [comment]
@muggsyd Hi, 
Thank you already for your comment.

So indeed the first thing is this docker for pyautorescene is based on my fork of pyautorescene and not on the original script.

Anyway there is a problem with the versions of python for the time.time () function has become obsolete after python 3.6 or 3.7 if I remember however the last version of the code of PyRescene available on github allows to solve this problem it is besides this version which is recovered in my docker before installing my fork of pyautorescene.

The user / password are only necessary for my pyautorescene script fork which is here: https://github.com/jaloji/pyautorescene

This is due to the simple fact that if you are not logged in to download the .srr files then you have a daily limit my fork is precisely to avoid this limit.

Regarding the Winrar executables on linux for the moment I have not implemented it in my script and in my docker I simply did not test it yet (to see if it really works) and if not, I will get them in the same place.

Best regards

**Comment by muggsyd** [comment]
That's awesome. I'll follow your work
